In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("sample_real_estate_data.csv")

In [3]:
df.head(10)

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000.0
1  100002000.0   197.0   LEXINGTON            N            3        0   100.0
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12            1      NaN   700.0
4          NaN   203.0    BERKELEY            Y            3        2  1600.0
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y            1        1     NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800.0

In [4]:
df.isnull().sum()

PID             1
ST_NUM          2
ST_NAME         0
OWN_OCCUPIED    1
NUM_BEDROOMS    2
NUM_BATH        1
SQ_FT           1
dtype: int64

In [5]:
df["ST_NUM"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: ST_NUM, dtype: bool

In [6]:
df["NUM_BEDROOMS"].isnull()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
Name: NUM_BEDROOMS, dtype: bool

In [7]:
missing_value=['n/a','na','--']
df=pd.read_csv("sample_real_estate_data.csv",na_values=missing_value)
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0        0   100.0
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

In [8]:
from sklearn.impute import SimpleImputer

X = df.iloc[:,:-1].values
Y = df.iloc[:,6]
X

array([[100001000.0, 104.0, 'PUTNAM', 'Y', 3.0, '1'],
       [100002000.0, 197.0, 'LEXINGTON', 'N', 3.0, '0'],
       [100003000.0, nan, 'LEXINGTON', 'N', nan, '1'],
       [100004000.0, 201.0, 'BERKELEY', '12', 1.0, nan],
       [nan, 203.0, 'BERKELEY', 'Y', 3.0, '2'],
       [100006000.0, 207.0, 'BERKELEY', 'Y', nan, '1'],
       [100007000.0, nan, 'WASHINGTON', nan, 2.0, 'HURLEY'],
       [100008000.0, 213.0, 'TREMONT', 'Y', 1.0, '1'],
       [100009000.0, 215.0, 'TREMONT', 'Y', nan, '2']], dtype=object)

In [9]:
Y

0    1000.0
1     100.0
2     850.0
3     700.0
4    1600.0
5     800.0
6     950.0
7       NaN
8    1800.0
Name: SQ_FT, dtype: float64

In [10]:
impute = SimpleImputer(missing_values =np.nan, strategy ='mean')
impute = impute.fit(X[:,1:2])
X[:,1:2] = impute.transform(X[:,1:2])
X[:,1:2]

array([[104.0],
       [197.0],
       [191.42857142857142],
       [201.0],
       [203.0],
       [207.0],
       [191.42857142857142],
       [213.0],
       [215.0]], dtype=object)

In [11]:

df['NUM_BEDROOMS'].fillna(df['NUM_BEDROOMS'].median(), inplace=True)
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0        0   100.0
2  100003000.0     NaN   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0

In [12]:
df['ST_NUM'].fillna(df['ST_NUM'].mean(), inplace=True)
df

PID      ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH  \
0  100001000.0  104.000000      PUTNAM            Y           3.0        1   
1  100002000.0  197.000000   LEXINGTON            N           3.0        0   
2  100003000.0  191.428571   LEXINGTON            N           2.5        1   
3  100004000.0  201.000000    BERKELEY           12           1.0      NaN   
4          NaN  203.000000    BERKELEY            Y           3.0        2   
5  100006000.0  207.000000    BERKELEY            Y           2.5        1   
6  100007000.0  191.428571  WASHINGTON          NaN           2.0   HURLEY   
7  100008000.0  213.000000     TREMONT            Y           1.0        1   
8  100009000.0  215.000000     TREMONT            Y           2.5        2   

    SQ_FT  
0  1000.0  
1   100.0  
2   850.0  
3   700.0  
4  1600.0  
5   800.0  
6   950.0  
7     NaN  
8  1800.0

One Hot Encoding 

In [13]:
df=pd.read_csv('MallCustomers.CSV')
df.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [14]:
X = df.iloc[:,:-1].values
y = df.iloc[:,4].values

In [15]:
from sklearn.preprocessing import LabelEncoder
lablencode= LabelEncoder()
X[:,1] = lablencode.fit_transform(X[:,1])
X

array([[1, 1, 19, 15],
       [2, 1, 21, 15],
       [3, 0, 20, 16],
       [4, 0, 23, 16],
       [5, 0, 31, 17],
       [6, 0, 22, 17],
       [7, 0, 35, 18],
       [8, 0, 23, 18],
       [9, 1, 64, 19],
       [10, 0, 30, 19],
       [11, 1, 67, 19],
       [12, 0, 35, 19],
       [13, 0, 58, 20],
       [14, 0, 24, 20],
       [15, 1, 37, 20],
       [16, 1, 22, 20],
       [17, 0, 35, 21],
       [18, 1, 20, 21],
       [19, 1, 52, 23],
       [20, 0, 35, 23],
       [21, 1, 35, 24],
       [22, 1, 25, 24],
       [23, 0, 46, 25],
       [24, 1, 31, 25],
       [25, 0, 54, 28],
       [26, 1, 29, 28],
       [27, 0, 45, 28],
       [28, 1, 35, 28],
       [29, 0, 40, 29],
       [30, 0, 23, 29],
       [31, 1, 60, 30],
       [32, 0, 21, 30],
       [33, 1, 53, 33],
       [34, 1, 18, 33],
       [35, 0, 49, 33],
       [36, 0, 21, 33],
       [37, 0, 42, 34],
       [38, 0, 30, 34],
       [39, 0, 36, 37],
       [40, 0, 20, 37],
       [41, 0, 65, 38],
       [42, 1, 24, 38],
 

In [16]:
from sklearn.preprocessing import OneHotEncoder
onehotencod = OneHotEncoder(sparse = False)


In [17]:
onehotencod.fit_transform(df[["Gender"]])


array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

Test Set & Feature Scaling 

In [18]:
df=pd.read_csv('diabetes.csv')

In [19]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  Unnamed: 9 Unnamed: 10  \
0                     0.627   50        1         NaN         NaN   
1                     0.351   31        0         NaN         NaN   
2                     0.672   32        1         NaN         NaN   
3                     0.167   21        0         NaN         NaN   
4                     2.288   33        1         NaN         NaN   

   Unnamed: 11 Unnamed: 12  
0          NaN         NaN  
1          NaN         NaN  
2          NaN         NaN  
3          NaN         NaN  
4          NaN         NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
 9   Unnamed: 9                0 non-null      float64
 10  Unnamed: 10               2 non-null      object 
 11  Unnamed: 11               0 non-null      float64
 12  Unnamed: 12               2 non-null      object 
dtypes: float64(4), int64(7), object(2)
memory usage: 78.1+ KB


In [22]:
df['Pregnancies'] = pd.to_numeric(df['Pregnancies'],errors='coerce')

In [23]:
df['Pregnancies']=df['Pregnancies'].astype('float')
df=df.drop(df['Pregnancies'])

In [24]:
X = df.iloc[:,:-1].values 
y = df.iloc[:,8].values
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
16          0.0      118             84             47      230  45.8   
18          1.0      103             30             38       83  43.3   
19          1.0      115             70             30       96  34.6   
20          3.0      126             88             41      235  39.3   
21          8.0       99             84              0        0  35.4   

    DiabetesPedigreeFunction  Age  Outcome  Unnamed: 9 Unnamed: 10  \
16                     0.551   31        1         NaN         NaN   
18                     0.183   33        0         NaN         NaN   
19                     0.529   32        1         NaN         NaN   
20                     0.704   27        0         NaN         NaN   
21                     0.388   50        0         NaN         NaN   

    Unnamed: 11 Unnamed: 12  
16          NaN         NaN  
18          NaN         NaN  
19          NaN         NaN  
20          NaN         NaN  
21          NaN         NaN

In [25]:
df['Pregnancies'].isnull().sum()

0

In [26]:
df['Pregnancies']=df['Pregnancies'].astype('int32')

In [27]:
X

array([[0.0, 118, 84, ..., nan, nan, nan],
       [1.0, 103, 30, ..., nan, nan, nan],
       [1.0, 115, 70, ..., nan, nan, nan],
       ...,
       [5.0, 121, 72, ..., nan, nan, nan],
       [1.0, 126, 60, ..., nan, nan, nan],
       [1.0, 93, 70, ..., nan, nan, nan]], dtype=object)

In [29]:
y

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [32]:
X_train[:,0]

array([4.0, 5.0, 0.0, 1.0, 2.0, 4.0, 7.0, 0.0, 3.0, 5.0, 3.0, 1.0, 6.0,
       2.0, 2.0, 1.0, 3.0, 0.0, 4.0, 3.0, 3.0, 4.0, 8.0, 1.0, 5.0, 1.0,
       8.0, 2.0, 5.0, 0.0, 0.0, 0.0, 7.0, 0.0, 2.0, 7.0, 0.0, 6.0, 3.0,
       0.0, 1.0, 7.0, 4.0, 9.0, 1.0, 0.0, 3.0, 6.0, 13.0, 1.0, 0.0, 6.0,
       3.0, 4.0, 1.0, 1.0, 3.0, 1.0, 9.0, 8.0, 7.0, 5.0, 7.0, 5.0, 2.0,
       9.0, 2.0, 7.0, 4.0, 1.0, 8.0, 10.0, 5.0, 2.0, 3.0, 1.0, 2.0, 3.0,
       11.0, 5.0, 2.0, 9.0, 2.0, 10.0, 4.0, 1.0, 4.0, 6.0, 1.0, 1.0, 3.0,
       2.0, 9.0, 4.0, 7.0, 1.0, 6.0, 4.0, 2.0, 2.0, 1.0, 6.0, 0.0, 4.0,
       10.0, 4.0, 1.0, 0.0, 6.0, 2.0, 2.0, 1.0, 2.0, 0.0, 1.0, 2.0, 5.0,
       4.0, 3.0, 8.0, 1.0, 2.0, 7.0, 2.0, 2.0, 3.0, 8.0, 1.0, 4.0, 0.0,
       1.0, 2.0, 1.0, 3.0, 3.0, 2.0, 1.0, 1.0, 0.0, 3.0, 6.0, 8.0, 5.0,
       11.0, 5.0, 10.0, 3.0, 1.0, 6.0, 12.0, 13.0, 2.0, 9.0, 6.0, 2.0,
       8.0, 1.0, 2.0, 1.0, 4.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 5.0, 2.0,
       0.0, 8.0, 9.0, 4.0, 1.0, 2.0, 9.0, 9.0, 8.0, 9.0, 5.0

In [34]:
from sklearn.preprocessing import StandardScaler
stdscalar = StandardScaler()
X_train = stdscalar.fit_transform(X_train)
X_test = stdscalar.transform(X_test)

C:\Users\Henry\Anaconda3\lib\site-packages\sklearn\utils\extmath.py:765: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\Henry\Anaconda3\lib\site-packages\sklearn\utils\extmath.py:706: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)


In [35]:
X_train

array([[ 0.07930132,  2.47376354,  0.07748196, ...,         nan,
                nan,         nan],
       [ 0.39028691, -0.46125521,  0.1773513 , ...,         nan,
                nan,         nan],
       [-1.16464101,  1.45288746,  1.07617537, ...,         nan,
                nan,         nan],
       ...,
       [ 0.70127249, -0.26984095, -0.22212606, ...,         nan,
                nan,         nan],
       [ 1.63422924, -0.97169326, -0.3219954 , ...,         nan,
                nan,         nan],
       [ 1.01225807,  2.05903263,  0.77656734, ...,         nan,
                nan,         nan]])